config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :boards,
    except: %i[destroy] do
      resources :lists,
        shallow: true do
          resources :tasks, path: 'cards', shallow: true
      end
  end

  root "boards#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
# frozen_string_literal: true

class Board < ApplicationRecord

  validates :name, presence: true

  has_many :lists

  store_accessor :trello,
    :id,
    :name,
    :url,
    prefix: true
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord

  has_many :cards, class_name: 'Task'

  belongs_to :board

end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord

  belongs_to :board

  validates :name, presence: true

  enum status: { todo: 0, doing: 1, done: 2, other: 99 } # REMOVE: no needed anymore

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
# frozen_string_literal: true

class BoardsController < ApplicationController

  def index
    find_trello_boards
    @boards ||= Board.all

    respond_to do |format|
      format.html
      format.json { render json: @boards.to_json }
    end
   end

  def show
    fetch_cards_for_board
    @board = board

    respond_to do |format|
      format.html
      format.json { render json: @board.to_json }
    end
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)

    if @board.valid?
      @board.save

      redirect_to board_path(@board)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

    def board
      @_board ||= Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:name)
    end

    def find_trello_boards
      @_find_trello_boards ||= AppServicesJob.perform_later(
        'Boards::GetTrelloBoardService'
      )
    end

    def fetch_cards_for_board
      @_fetch_cards_for_board ||= AppServicesJob.perform_later(
        'Boards::GetBoardCardsService',
        { board: board }
      )
    end

end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController

  def new
    @board ||= board
  end

  def create
    @board = board
    @list = board.lists.build(list_params)

    if @list.valid?
      # @list.save
      # Boards::CreateCardOnTrelloService.call(board: board, card: task)
      redirect_to board_path(board)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

    def board
      @_board ||= Board.find(params[:board_id])
    end

    def list_params
      params.require(:list).permit(:name, :board_id)
    end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController

  def new
    @list ||= list
  end

  def create
    @list = list
    @task = list.cards.build(task_params.merge({ board_id: list.board_id}))

    if @task.valid?
      @task.save

      AppServicesJob.perform_later(
        'Boards::CreateCardOnTrelloService',
        { list: list, card: @task }
      )

      redirect_to board_path(list.board)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
  end

  private

    def list
      @_list ||= List.find(params[:list_id])
    end

    def task_params
      params.require(:task).permit(:name, :description, :list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_board.html.erb
<%= content_tag(:li) do%>
  <%= link_to board.name, board, class: 'link', data: { turbo_frame: :_top } %>
<% end %>

app/views/boards/_boards.html.erb
    <%= content_tag(:section, id: :frameBoards) do %>
      <% boards.each do |board|%>
        <%= render 'boards/board', board: board %>
      <% end %>
    <% end %>

app/views/boards/index.html.erb
<%= turbo_frame_tag :frameAppHeader do %>
  <%= content_tag(:header, class: 'header') do %>
    <%= content_tag(:h1, t('app.brand_name'), class: 'h1 text-white') %>
  <% end %>
<% end %>

<%= turbo_stream_from :boards_stream %>
<%= content_tag(:section, class: 'main-layout') do%>
  <%= content_tag(:ul, class: 'divide-y') do %>
    <%= render 'boards/boards', boards: @boards %>
    <%= link_to t('app.boards.new'), new_board_path, class: 'underline' %>
  <% end %>
<% end %>

app/views/boards/new.html.erb
<%= turbo_frame_tag :frameBoards, target: :_top do %>
  <%= content_tag(:div, class: 'main-layout') do%>
    <%= form_with(model: @board, url: boards_path, local: true, data: { turbo: :false }) do |f|%>
      <%= f.label :name%>
      <%= f.text_field :name, placeholder: 'name', required: true %>

      <%= f.submit t('app.submit') %>
    <% end %>
  <% end %>
<% end %>

app/views/boards/show.html.erb
<%= turbo_frame_tag :frameAppHeader do %>
  <%= content_tag(:header, class: 'header') do %>
    <%= content_tag(:h1, @board.name, class: 'h1 text-white') %>
  <% end %>
<% end %>

<%= turbo_stream_from @board, :board_lists %>
<%= turbo_frame_tag "frameBoard-#{@board.id}" do %>
<%= content_tag(:div, class: 'main-layout') do%>
  <div class="my-4">
    <%= link_to t('app.back'), root_path, class: 'link', data: { turbo_frame: :_top } %>
  </div>

  <div id="frameBoardLists-<%= @board.id %>" class="grid grid-cols-1 md:grid-cols-3 gap-4 lg:gap-8">
    <% @board.lists.each do |list|%>
      <%= render 'lists/list', list: list %>
    <% end %>
  </div>
<% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lethathamo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= turbo_frame_tag :frameAppHeader %>
    <%= turbo_frame_tag :frameNewCardModal %>
    <main class="boards-container">
      <%= turbo_frame_tag :frameMainContainer do %>
        <%= yield %>
      <% end %>
    </main>
  </body>
</html>

app/views/lists/_list.html.erb
      <%= content_tag(:section, class: 'card-container') do%>
        <div class="flex items-center justify-between">
          <%= content_tag(:h3, list.name, class: 'h4') %>
          <%= link_to t('app.add'), new_list_task_path(list), class: 'link', data: { turbo_frame: :frameNewCardModal } %>
        </div>
        <%= turbo_stream_from list, :list_cards %>
        <%= content_tag(:section, id: "frameListCards-#{list.id}") do %>
          <% list.cards.each do |card|%>
            <%= render 'tasks/task', card: card %>
          <% end %>
        <% end %>
      <% end %>

app/views/tasks/_task.html.erb
<div class="card">
  <h4 class="card-text"><%= card.name %></h4>
</div>

app/views/tasks/new.html.erb
<%= turbo_frame_tag :frameNewCardModal, target: :_top do %>
<div class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>

    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

    <div class="relative inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-sm sm:w-full sm:p-6">
      <div>
      <%= content_tag(:div, class: 'main-layout') do%>
        <%= content_tag(:h3, t('app.new_card'), class: 'h4') %>
        <%= form_with(model: [@list, @list.cards.build], url: list_tasks_path(@list), local: true, data: { turbo: :false }) do |f|%>
          <%= f.label :name%>
          <%= f.text_field :name, placeholder: 'name', required: true %>

          <div class="mt-5 sm:mt-6">
            <%= f.submit t('app.submit'), class: 'btn-primary__block' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<% end %>
<%= turbo_frame_tag :frameNewCard do%>
  <%= content_tag(:div, class: 'main-layout') do%>
    <%= form_with(model: [@list, @list.cards.build], url: list_tasks_path(@list), local: true, data: { turbo: :false }) do |f|%>
      <%= f.label :name%>
      <%= f.text_field :name, placeholder: 'name', required: true %>

      <%= f.submit t('app.submit') %>
    <% end %>
  <% end %>
<% end %>